### ISSUE TITLE
The multi factor authentification with FIDO2 Token is not validated sufficient

### ISSUE THREAD

**Issue by AndreasDickow** [mkalioby/AutoDeploy#41]
when logging in, in the second step I'm asked to press the Button on the Fido2 token, If I don't press it and just switch to a login_requiered url, I can allready access restricted content, maybe the mfa2 middleware for processing requests is not included?

**Comment by mkalioby** [comment]
Nope, the probem is in your login function, you shouldn't call login before mfa as shown in README

**Comment by mkalioby** [comment]
Closed due to inactivity

**Comment by AndreasDickow** [comment]
true I had misimplemented the login

**Comment by mkalioby** [comment]
Great to know
